export const DEV_GOOGLE_FONTS = [
  'Amarante',
  'Faculty Glyphic',
  'Prosto One',
  'Orbitron',
  'Goldman',
  'Geo',
  'Iceland',
  'Genos',
  'Tektur',
  'Tomorrow',
  'Aclonica',
  'Merienda',
  'Lemonada',
  'Iansui',
  'Oregano',
  'Solitreo',
  'Gaegu',
  'Walter Turncoat',
  'Concert One',
  'Texturina',
  'MedievalSharp',
  'Jersey 25',
  'Rubik Dirt',
  'Gasoek One',
  'Galindo',
  'Kdam Thmor Pro',
  'Bungee Shade',
  'Stardos Stencil',
  'Saira Stencil One',
  'Sirin Stencil',
  'Metamorphous',
  'Moon Dance',
  'Felipa',
  'Jim Nightshade',
  'Port Lligat Slab',
  'Buda',
  'Aref Ruqaa',
  'Fira Sans',
  'Roboto',
  'Mukta',
  'Cabin',
  'Lilita One',
  'Signika',
  'Signika Negative',
  'Krub',
  'Lalezar',
  'Secular One',
  'Cantora One',
  
] 