import React, { Children, cloneElement, isValidElement, useRef, useEffect, useState } from 'react';

interface NoteAnchorProps {
  children: React.ReactNode;
}

interface MarginNoteElement extends React.ReactElement {
  props: {
    line?: number;
    [key: string]: any;
  };
}

export const NoteAnchor = ({ children }: NoteAnchorProps) => {
  const [lineHeightPx, setLineHeightPx] = useState(0);
  const anchorRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (anchorRef.current) {
      const pre = anchorRef.current.querySelector('pre');
      if (pre) {
        const style = getComputedStyle(pre);
        const fontSize = parseFloat(style.fontSize);
        const lineHeight = parseFloat(style.lineHeight);
        // If lineHeight is unitless, it's a multiplier of font-size.
        // getComputedStyle returns px value for line-height, so this check is tricky.
        // However, modern browser return computed px value for line-height.
        setLineHeightPx(lineHeight || fontSize * 1.75); // fallback to 1.75 multiplier
      }
    }
  }, []);

  const notes: React.ReactNode[] = [];
  const otherChildren: React.ReactNode[] = [];

  Children.forEach(children, child => {
    if (
      isValidElement(child) &&
      ((child.type as any).name === 'MarginNote' ||
       (child.type as any).displayName === 'MarginNote')
    ) {
      notes.push(child);
    } else {
      otherChildren.push(child);
    }
  });

  const positionedNotes = notes.map((note, index) => {
    const marginNote = note as MarginNoteElement;
    if (marginNote.props.line && lineHeightPx > 0) {
      const topValue = `${(marginNote.props.line - 1) * lineHeightPx}px`;
      return cloneElement(marginNote, {
        ...marginNote.props,
        key: `mn-positioned-${index}`,
        y: topValue,
        top: undefined,
      });
    }
    return cloneElement(marginNote, { ...marginNote.props, key: `mn-positioned-${index}` });
  });

  const elementChildren = Children.toArray(otherChildren).filter(child => {
    if (isValidElement(child)) {
      // Filter out empty paragraphs that might be generated by MDX from extra newlines
      if (
        child.type === 'p' &&
        (!child.props.children ||
          (Array.isArray(child.props.children) && child.props.children.length === 0))
      ) {
        return false;
      }
      return true; // Keep valid elements that are not empty paragraphs
    }
    return false; // Discard non-element children like strings, numbers, etc.
  });

  const lastContentElement = elementChildren[elementChildren.length - 1];
  const endsWithPre = lastContentElement && lastContentElement.type === 'pre';

  const wrapperClassName = `note-anchor-wrapper ${endsWithPre ? 'ends-with-pre' : ''}`;

  return (
    <div style={{ position: 'relative' }} ref={anchorRef} className={wrapperClassName}>
      {otherChildren}
      {positionedNotes}
    </div>
  );
}; 