import fs from 'fs/promises';
import path from 'path';
import https from 'https';

const THEMES_DIR = path.join(process.cwd(), 'styles/code-themes');
const CONFIG_PATH = path.join(process.cwd(), 'lib/config/code-syntax-themes.ts');
const OUTPUT_PATH = path.join(process.cwd(), 'lib/active-code-themes.ts');
const CDN_BASE_URL = 'https://cdn.jsdelivr.net/npm/highlight.js@11.9.0/styles/';

/**
 * Fetches content from a URL.
 * @param {string} url - The URL to fetch from.
 * @returns {Promise<string>} The content of the URL.
 */
function fetchUrl(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        // Handle redirect
        return fetchUrl(res.headers.location).then(resolve, reject);
      }
      if (res.statusCode < 200 || res.statusCode >= 300) {
        return reject(new Error(`Download failed with status code: ${res.statusCode}`));
      }
      let data = '';
      res.on('data', (chunk) => (data += chunk));
      res.on('end', () => resolve(data));
    }).on('error', reject);
  });
}

/**
 * Reads the code syntax themes config file and extracts the theme names.
 * @returns {Promise<{lightTheme: string, darkTheme: string}>} An object containing the theme names.
 */
async function getThemeNamesFromConfig() {
  const configFileContent = await fs.readFile(CONFIG_PATH, 'utf-8');
  const lightThemeMatch = configFileContent.match(/lightTheme:\s*['"]([^'"]+)['"]/);
  const darkThemeMatch = configFileContent.match(/darkTheme:\s*['"]([^'"]+)['"]/);
  
  if (!lightThemeMatch || !darkThemeMatch) {
    throw new Error('Could not find lightTheme or darkTheme in lib/config/code-syntax-themes.ts');
  }
  
  return {
    lightTheme: lightThemeMatch[1],
    darkTheme: darkThemeMatch[1],
  };
}

/**
 * Downloads a theme if it doesn't exist locally.
 * @param {string} themeName - The name of the theme (e.g., 'github-dark').
 * @returns {Promise<string>} The CSS content of the downloaded theme.
 */
async function downloadTheme(themeName) {
  const filePath = path.join(THEMES_DIR, `${themeName}.css`);
  try {
    await fs.access(filePath);
  } catch {
    console.log(`Theme '${themeName}' not found. Downloading...`);
    const url = `${CDN_BASE_URL}${themeName}.css`;
    try {
      const cssContent = await fetchUrl(url);
      await fs.writeFile(filePath, cssContent);
      console.log(`Successfully downloaded and saved '${themeName}'.`);
    } catch (error) {
      console.error(`Error downloading theme '${themeName}' from ${url}:`, error.message);
    }
  }
  return fs.readFile(filePath, 'utf-8');
}

/**
 * Main function to run the theme building process.
 */
async function main() {
  try {
    await fs.mkdir(THEMES_DIR, { recursive: true });
    const { lightTheme, darkTheme } = await getThemeNamesFromConfig();
    
    console.log(`Required themes: Light - ${lightTheme}, Dark - ${darkTheme}`);
    
    const lightThemeCss = await downloadTheme(lightTheme);
    const darkThemeCss = await downloadTheme(darkTheme);

    const outputContent = `// This file is auto-generated by scripts/build-themes.mjs. Do not edit.
export const lightThemeCss = \`${lightThemeCss.replace(/`/g, '\\`')}\`;
export const darkThemeCss = \`${darkThemeCss.replace(/`/g, '\\`')}\`;
`;

    await fs.writeFile(OUTPUT_PATH, outputContent);
    console.log(`Successfully built active themes to ${OUTPUT_PATH}`);

  } catch (error) {
    console.error('An error occurred during theme processing:', error);
    process.exit(1);
  }
}

main(); 